[package]
name = "mmap-bitvec"
version = "0.1.1"
authors = ["Roderick Bovee <roderick@onecodex.com>"]

[dependencies]
memmap = "0.6.2"
murmurhash3 = "0.0.5"

[features]
u128 = []
backward_bytes = []

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "benchmark"
harness = false
