[package]
name = "mmap-bitvec"
version = "0.3.0"
authors = ["Roderick Bovee <roderick@onecodex.com>"]

[dependencies]
memmap = "0.6.2"
murmurhash3 = "0.0.5"

[features]
backward_bytes = []
rank_lookup = []
