[package]
name = "mmap-bitvec"
version = "0.3.1"
authors = ["Roderick Bovee <roderick@onecodex.com>"]
autobenches = false
edition = "2018"

[dependencies]
memmap = "0.7.0"
murmurhash3 = "0.0.5"
once_cell = "1.3.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmark"
harness = false