version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:1.40
    steps:
      - checkout
      - run:
          name: Version information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Calculate dependencies
          command: cargo generate-lockfile
      - restore_cache:
          keys:
            - v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Build all targets
          command: cargo build --all --all-targets
      - save_cache:
          paths:
            - ~/.cargo/registry
            - ~/.cargo/bin/cargo-tarpaulin
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: v4-cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run:
          name: Format
          command: |
            rustup component add rustfmt
            cargo fmt -- --check
      - run:
          name: Clippy
          command: |
            rustup component add clippy
            cargo clippy --all --
      - run:
          name: Run all tests
          command: cargo test --all
