name: ci
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [pinned, stable]
        include:
        - build: pinned
          os: ubuntu-22.04
          rust: 1.60.0
        - build: stable
          os: ubuntu-22.04
          rust: stable
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build System Info
      run: rustc --version
    - name: Run tests
      run: cargo test
