name: ci
on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build: [pinned, stable]
        include:
        - build: pinned
          os: ubuntu-18.04
          rust: 1.40.0
        - build: stable
          os: ubuntu-18.04
          rust: stable
    steps:
    - uses: actions/checkout@v1
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - name: Build System Info
      run: rustc --version
    - name: Run tests
      run: cargo test
    - name: Run tests with features
      run: RUST_TEST_THREADS=1 cargo test --features marker_lookup
